# Generated by Django 6.0.1 on 2026-07-22 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('lunch', 'Lunch'), ('sunset_cruise', 'Sunset Cruise')], default='sunset_cruise', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('includes', models.TextField(blank=True, help_text='Details of what is included (e.g. welcome drink, full course meal)', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
