# Generated by Django 6.0.1 on 2026-07-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_package_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='meal_type',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('sunset_cruise', 'Sunset Cruise'), ('booze_cruise', 'Booze Cruise'), ('special_cruise', 'Special Cruise'), ('dinner_cruise', 'Dinner Cruise'), ('exclusive_cruise', 'Exclusive Cruise')], default='sunset_cruise', max_length=50),
        ),
    ]
