# Generated by Django 6.0.1 on 2026-07-22 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dhow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('meal_type', models.CharField(choices=[('lunch', 'Lunch'), ('sunset_cruise', 'Sunset Cruise')], default='sunset_cruise', max_length=50)),
                ('departure_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('days_of_week', models.JSONField(default=list, help_text="List of days of week (e.g. ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'])")),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('exclusive_flat_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_templates_created', to=settings.AUTH_USER_MODEL)),
                ('dhow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='dhow.dhow')),
            ],
            options={
                'verbose_name': 'Schedule Template',
                'verbose_name_plural': 'Schedule Templates',
                'ordering': ['dhow', 'departure_time'],
            },
        ),
    ]
