# Generated by Django 6.0.1 on 2026-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletemplate',
            name='meal_type',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('sunset_cruise', 'Sunset Cruise'), ('booze_cruise', 'Booze Cruise'), ('special_cruise', 'Special Cruise'), ('dinner_cruise', 'Dinner Cruise')], default='sunset_cruise', max_length=50),
        ),
    ]
