# Generated by Django 6.0.1 on 2026-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_template', '0002_alter_scheduletemplate_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletemplate',
            name='price_per_child',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
