# Generated by Django 6.0.1 on 2026-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingguest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked In'), ('no_show', 'No Show')], default='pending', max_length=50),
        ),
    ]
