# Generated by Django 6.0.1 on 2026-07-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_guest', '0002_bookingguest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingguest',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
