# Generated by Django 6.0.1 on 2026-07-22 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('agent_credit', 'Agent Credit'), ('waived', 'Waived')], default='mpesa', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing STK Push'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_ref', models.CharField(blank=True, help_text='M-Pesa CheckoutRequestID or external reference', max_length=255, null=True)),
                ('receipt_number', models.CharField(blank=True, help_text='M-Pesa Receipt Number (e.g. QX12345678)', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='M-Pesa phone number used', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
