# Generated by Django 6.0.1 on 2026-07-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('agent_credit', 'Agent Credit'), ('waived', 'Waived'), ('staff_card', 'Staff Card'), ('mastercard', 'Mastercard'), ('visa', 'Visa')], default='mpesa', max_length=50),
        ),
    ]
