# Generated by Django 6.0.1 on 2026-05-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_is_approved_user_is_agent_user_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_no",
            new_name="usercode",
        ),
    ]
