# Generated by Django 6.0.1 on 2026-07-22 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('booking_type', models.CharField(choices=[('individual', 'Individual'), ('group_agent', 'Group (Agent)'), ('exclusive', 'Exclusive Charter'), ('walk_in', 'Walk-In')], default='individual', max_length=50)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=50)),
                ('cancellation_preference', models.CharField(choices=[('reschedule', 'Reschedule'), ('refund', 'Refund')], default='refund', help_text="Guest's preference if the sailing is cancelled (Reschedule or Refund)", max_length=50)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('exclusive_note', models.TextField(blank=True, null=True)),
                ('table_request', models.CharField(blank=True, help_text='Requested seating preference (e.g. deck seat, window table)', max_length=255, null=True)),
                ('special_requests', models.TextField(blank=True, help_text='e.g. Birthday setup, Vegan meal', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Manager or agent internal notes', null=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='package.package')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
