# Generated by Django 6.0.1 on 2026-07-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Discount amount in KES applied to the booking', max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Reason for the discount', max_length=255, null=True),
        ),
    ]
