# Generated by Django 6.0.1 on 2026-07-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_discount_amount_booking_discount_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_price_per_child',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override standard child price per person', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='custom_price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override standard adult price per person', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_type',
            field=models.CharField(choices=[('amount', 'Flat Amount'), ('percentage', 'Percentage')], default='amount', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentage value or flat KES amount', max_digits=12),
        ),
    ]
