# Generated by Django 6.0.1 on 2026-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_custom_price_per_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancellation_preference',
            field=models.CharField(choices=[('reschedule', 'Reschedule'), ('refund', 'Refund'), ('confirmed', 'Confirmed (Sailing Guaranteed)')], default='refund', help_text="Guest's preference if the sailing is cancelled (Reschedule or Refund)", max_length=50),
        ),
    ]
