# Generated by Django 6.0.1 on 2026-08-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_cancellation_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table_allocation',
            field=models.CharField(blank=True, help_text='Direct table allocation name/number (e.g. Table 5, T10)', max_length=255, null=True),
        ),
    ]
