# Generated by Django 6.0.1 on 2026-07-22 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addon', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAddOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price snapshot at time of booking', max_digits=12)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_addons', to='addon.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_addons', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Booking Add-On',
                'verbose_name_plural': 'Booking Add-Ons',
                'ordering': ['booking', 'addon'],
            },
        ),
    ]
