# Generated by Django 6.0.1 on 2026-07-22 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dhow', '0001_initial'),
        ('schedule_template', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('lunch', 'Lunch'), ('sunset_cruise', 'Sunset Cruise')], default='sunset_cruise', max_length=50)),
                ('departure_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('exclusive_flat_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=50)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True, help_text='Manager can open or close bookings for this schedule')),
                ('cancelled_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL)),
                ('dhow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dhow.dhow')),
                ('exclusive_booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_schedules', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_schedules', to='schedule_template.scheduletemplate')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['date', 'departure_time'],
            },
        ),
    ]
