# Generated by Django 6.0.1 on 2026-07-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_price_per_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='manifest_token',
            field=models.CharField(blank=True, help_text='Permanent public manifest sharing token (UUID hex)', max_length=64, null=True, unique=True),
        ),
    ]
