# Generated by Django 6.0.1 on 2026-07-22 12:53

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dhow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_capacity', models.PositiveIntegerField(default=50, help_text='Maximum guests vessel can physically accommodate')),
                ('min_quota', models.PositiveIntegerField(default=10, help_text='Minimum confirmed guests required to sail')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dhows_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dhow',
                'verbose_name_plural': 'Dhows',
                'ordering': ['-created_at'],
            },
        ),
    ]
