# Generated by Django 6.0.1 on 2026-07-22 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('holding', 'Holding in Escrow'), ('released_to_finance', 'Released to Finance'), ('reversed_to_guest', 'Reversed to Guest'), ('failed', 'Escrow Failed')], default='holding', max_length=50)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_method', models.CharField(blank=True, choices=[('schedule_confirmed', 'Schedule Confirmed'), ('schedule_cancelled', 'Schedule Cancelled'), ('manual_override', 'Manual Override')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='payment.payment')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_records', to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Escrow Record',
                'verbose_name_plural': 'Escrow Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
