# Generated by Django 6.0.1 on 2026-07-22 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReschedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending New Schedule Choice'), ('confirmed', 'Reschedule Confirmed'), ('rejected', 'Reschedule Rejected')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='booking.booking')),
                ('new_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='schedule.schedule')),
                ('original_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescheduled_from', to='schedule.schedule')),
                ('rescheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedules_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Reschedule',
                'verbose_name_plural': 'Booking Reschedules',
                'ordering': ['-created_at'],
            },
        ),
    ]
