# Generated by Django 6.0.1 on 2026-07-22 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_number', models.CharField(help_text='e.g. T1, T2, Deck-1', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Number of seats at this table')),
                ('description', models.TextField(blank=True, help_text='e.g. window seat, upper deck front', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Booking assigned to this table by manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to='booking.booking')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['schedule', 'table_number'],
            },
        ),
    ]
